spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_app
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent-output=true

google.client.id=342685303418-fhlop56kmo3d7f4vjn5t6jes1tt7tg4h.apps.googleusercontent.com


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenhaanha45285@gmail.com
spring.mail.password=kirawxshifdvprfp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8081
server.address=0.0.0.0

# VNPAY Configuration
vnpay.tmnCode=LEDMG40Y
vnpay.hashSecret=2MCQXCBWL51L1EQSR0AIFAFPXB97Z9YM
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=https://ecommerce-app/vnpay-return
>>>>>>> origin/user-home
